SELECT * FROM "EMPLOYEE DATA"

SELECT EDUCATION, CITY, AGE
FROM "EMPLOYEE DATA"
WHERE EDUCATION = 'Bachelors'
AND AGE < 38
AND CITY != 'Pune'

SELECT DISTINCT EDUCATION, CITY, AGE
FROM "EMPLOYEE DATA"
GROUP BY EDUCATION, CITY, AGE
ORDER BY AGE ASC;

SELECT  UPPER(CITY) AS GREAT
FROM "EMPLOYEE DATA"


--CONCAT
SELECT EDUCATION, JOININGYEAR,
CONCAT(EDUCATION,' , ', JOININGYEAR) AS "GRADUATION YEAR"
FROM "EMPLOYEE DATA"


--GROUPBY AND HAVING
SELECT DISTINCT EDUCATION, CITY, AGE
FROM "EMPLOYEE DATA"
GROUP BY EDUCATION, CITY, AGE
HAVING AGE BETWEEN 20 AND 30;

--CASE STATEMENT
SELECT  EDUCATION, CITY, AGE,
CASE
	WHEN AGE <=25 THEN 'FRESHER'
	WHEN AGE BETWEEN 26 AND 30 THEN 'MID YEAR'
	WHEN AGE > 30 THEN 'OUGHT TO GRADUATE'
END AS "STUDENT STATUS"
FROM "EMPLOYEE DATA";


